---
title: "lab09-mk-larson"
author: "mklarson"
date: "October 25, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, eval = FALSE}
library(testthat)
```
```{r}
head(USArrests)
states <- rownames(USArrests)
```

```{r}
nchar(states)
num_chars <- nchar(states)
char_freqs <- table(num_chars)
barplot(char_freqs, main = "Frequencies of lengths of state names")
```

```{r}
c <- c(7, 6, 7, 8, 10)
states_and_length <- paste(head(states), c , sep = ' = ')
states_collapse <- paste(head(states), collapse = '')
states_collapse
states_and_length
# of permutations of the string "Alamaba" is just 7!
num_permutations <- factorial(7)
num_permutations
```

```{r}
first_three_letters <- substr(states, 1, 3)
first_three_letters
last_three_letters <- substr(states, nchar(states)-2, nchar(states))
last_three_letters
shorten_names <- paste0(first_three_letters, last_three_letters)
shorten_names
```

```{r}
states_list <- list()
for (i in 4:14){
  if (i %% 2==0){
    states_list <- c(states_list, toupper(paste(states[nchar(states)==i], collapse= ", ")))
  }
  else{
    states_list <- c(states_list, paste(states[nchar(states)==i], collapse= ", "))
  }
}
names(states_list) <- c("4-chars","5-chars","6-chars","7-chars","8-chars","9-chars","10-chars","11-chars","12-chars","13-chars","14-chars")
states_list
```

```{r}
to_celsius <- function(x = 1) {
  (x - 32) * (5/9)
}

to_kelvin <- function(x = 1) {
  (x + 459.67) * (5/9)
}

to_reaumur <- function(x = 1) {
  (x - 32) * (4/9)
}

to_rankine <- function(x = 1) {
  x + 459.67
}

temp_convert <- function(x = 1, to = "celsius") {
  toupper(to)
  switch(to,
         "CELSIUS" = to_celsius(x),
         "KELVIN" = to_kelvin(x),
         "REAUMUR" = to_reaumur(x),
         "RANKINE" = to_rankine(x))
}

temp_convert(30, 'celsius')
temp_convert(30, 'Celsius')
temp_convert(30, 'CELSIUS')
```

```{r}
files <- paste0("file", 1:10, ".csv")
paste("file", 1:10, ".csv", sep = '')
g <- seq(from = 1, to = 10, by = 1)
paste("file", g, ".csv", sep = '')
data_sets <- gsub("file", "dataset", files)
data_sets
```

```{r}
# name of output file
outfile <- "output.txt"

# writing to 'outfile.txt'
cat(" ", file = outfile)
# insert new line
cat("\n", file = outfile, append = TRUE)
cat("----------", file = "output.txt", append = TRUE)
# insert 2 new lines
cat("\ntitle: Lab09\n", file = outfile, append = TRUE)
cat("\nauthor: MK Larson\n",
    file = outfile, append = TRUE)
cat("\ndate: 10-27-2018\n", file = outfile, append = TRUE)
cat("\noutput: html_document\n", file = outfile, append = TRUE)
```

```{r}
is_color <- function(x){
  x %in% colors()
}
is_color('yellow')  # TRUE

is_color('blu')     # FALSE

is_color('turkuoise') # FALSE
colplot <- function(col){
  if (is_color(col)==FALSE){
    stop(paste("invalid color", col))
  }
  else {
    plot(x = rnorm(10), y = rnorm(10), main = paste("Testing Color", col))
  }
}
colplot('tomato')
```

